### PR TITLE
Fix Makefile to allow debianization to work properly

### PR DESCRIPTION
**Pull request by hotice**
This should fix the package not building in your PPA.

### CODE REVIEW

**Comment by LeoIannacone** [comment]
What's the problem exactly with my PPA ?

**Comment by hotice** [comment]
The PPA is actually empty because all the packages failed to build: https://launchpad.net/~l3on/+archive/ubuntu/indicator-lockkeys/+packages

**Comment by hotice** [comment]
The reason being that you're not using relative paths in the makefile: 

```
mkdir -p /usr/share/icons/ubuntu-mono-dark/status/22/
mkdir: cannot create directory '/usr/share/icons': Permission denied
Makefile:31: recipe for target 'install_icons' failed
make[1]: *** [install_icons] Error 1
```

Build log here: https://launchpadlibrarian.net/207921335/buildlog_ubuntu-utopic-amd64.indicator-lockkeys_0.0.0-0~utopic_BUILD:ING.txt.gz

With my changes, the package should be built properly on launchpad. Also, you can remove the "install" file from the debian folder (I forgot to do that in my commit) since the makefile now takes care of everything.

**Comment by LeoIannacone** [comment]
You could you please remove it by yourself? I will be more than happy to merge this PR then

**Comment by LeoIannacone** [comment]
Please, also provide a buildlog that proves these changes fix the issue

**Comment by hotice** [comment]
You could have uploaded it and see if it works, it only takes a few seconds :) . Anyway, here's the package built successfully in my test PPA: https://launchpad.net/~nilarimogard/+archive/ubuntu/test/+packages?field.name_filter=lockkeys&field.status_filter=published&field.series_filter= You can click the 'expand arrow' icon and see the source (and compare it to the changes I pushed here), see the log, download the deb, etc. 

I was just trying to help since your packages failed to build and there are no actual debs in your PPA: http://ppa.launchpad.net/l3on/indicator-lockkeys/ubuntu/pool/main/i/indicator-lockkeys/ ...

I'll push the change with the debian/install file removal shortly.

**Comment by LeoIannacone** [comment]
Still some issue with PPA. Will look when I will have time. In the meanwhile, if you have any suggestion, please .. report :)

**Comment by hotice** [comment]
It fails for Ubuntu versions older than Vivid because:

```
valac --vapidir vapi/ \
          --pkg appindicator3-0.1 \
          --pkg caribou-1.0 \
          --pkg gtk+-3.0 \
          *.vala
error: Package `caribou-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
```

I guess the valac package in the official Ubuntu 14.04 and 12.04 repositories is too old. It might also happen because Ubuntu versions older than Vivid have a too old Caribou package and if that's the case, there's nothing you can do (you can upload a newer version to your PPA but it might cause issues so I don't recommend it). 

If it's because of too old Vala there is a workaround you can use: you can add the Vala PPA as a dependency to your PPA. To do this, on your PPA page select "Edit PPA dependencies" from the top right and then in the "Add PPA dependency:" field enter "vala-team/ppa". 

Then, in the indicator-lockkeys debian/control file, for the "build-depends", replace "valac" with "valac-0.26" (I assume vala 0.26 will work but if it doesn't, you can take a look at the Vala PPA: https://launchpad.net/~vala-team/+archive/ubuntu/ppa to see the Vala versions it provides and use a different version as a dependency for your package.

**Comment by LeoIannacone** [comment]
Ok, considering this, I can say that I won't support old Ubuntu version.

Thank you for helping!

L.

**Comment by hotice** [comment]
You're welcome!

By the way, I just tried it in my test PPA and it's indeed because of a too old Caribou version in Trusty (and older), not because of Vala.

**Pull request merged**
